font:
  size: 15.0
  normal:
    family: "JetBrains Mono"
    style: Regular

  bold:
    family: "JetBrains Mono"
    style: Bold

  italic:
    family: "JetBrains Mono"
    style: Italic

  bold_italic:
    family: "JetBrains Mono"
    style: Bold Italic

# Ayu Mirage
colors:
  # Default colors
  primary:
    background: '#202734'
    foreground: '#CBCCC6'

  # Normal colors
  normal:
    black: '#191E2A'
    red: '#FF3333'
    green: '#BAE67E'
    yellow: '#FFA759'
    blue: '#73D0FF'
    magenta: '#FFD580'
    cyan: '#95E6CB'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F27983'
    green: '#A6CC70'
    yellow: '#FFCC66'
    blue: '#5CCFE6'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'

key_bindings:
  - { key: N,      mods: Control, action: SpawnNewInstance }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Minus,  mods: Control, action: DecreaseFontSize }
  - { key: Q, mods: Control, chars: "\x11" }
